version: 2.1
orbs:
  node: circleci/node@5.1.0

jobs:
  install:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn

  test:
    executor: node/default
    steps:
      - run:
          command: yarn test
          name: Run tests

workflows:
  test_app:
    jobs:
      - install
      - test:
          requires:
            - install
